server:
  port: 8055

spring:
  application:
    name: advanced-search
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/advanced-search
    username: wk-projects
    password: admin
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    database: postgresql
  liquibase:
    change-log: classpath:/db/master.xml
